### ISSUE TITLE
Fourth parameter of cf_j_neck is not working [ECABMX 3.1]

### ISSUE THREAD

**Issue by CodyLTH** [ManlyMarco/KKABMX#3]

**Comment by CodyLTH** [comment]
For male character

**Comment by ManlyMarco** [comment]
Hello,

I assume you were using advanced mode. Some sliders will not work in this mode because of a few different reasons. Only the sliders added to regular maker interface have been tested and proven working correctly.

That being said the upcoming release adds some improvements to handling lengths (4th slider), so it might help your case.
